source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'sqlite3'
gem 'bigpipe-rails', :require => "bigpipe_rails"

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'mocha'
  gem 'unicorn'
  gem 'factory_girl_rails'
  gem 'rails3-generators'
  gem 'growl'
end
